# Generated by Django 2.2.6 on 2020-05-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=2)),
                ('contact', models.CharField(default='', max_length=13)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Gender')),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'ordering': ['-date'],
            },
        ),
    ]
