# Generated by Django 2.2.6 on 2020-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200510_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
